config/routes.rb
Julekalender::Application.routes.draw do
  resources :questions_options

  resources :users
  resources :sessions

  resources :questions

  resources :answers
  match '/signup', to: "users#new", via: [:post,:get]
  match '/login', to: "sessions#new", via: [:post,:get]
  match "logout", to: "sessions#destroy", :as => "logout", via: [:post,:get]

  root :to => 'home#index'

end

app/models/questions_option.rb
class QuestionsOption < ActiveRecord::Base
  belongs_to :question
end

app/controllers/questions_options_controller.rb
class QuestionsOptionsController < ApplicationController
  # GET /questions_options
  # GET /questions_options.json
  def index
    @questions_options = QuestionsOption.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions_options }
    end
  end

  # GET /questions_options/1
  # GET /questions_options/1.json
  def show
    @questions_option = QuestionsOption.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questions_option }
    end
  end

  # GET /questions_options/new
  # GET /questions_options/new.json
  def new
    @questions_option = QuestionsOption.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questions_option }
    end
  end

  # GET /questions_options/1/edit
  def edit
    @questions_option = QuestionsOption.find(params[:id])
  end

  # POST /questions_options
  # POST /questions_options.json
  def create
    params[:questions_option][:correct].to_i
    @questions_option = QuestionsOption.new(questions_option_params)

    respond_to do |format|
      if @questions_option.save
        format.html { redirect_to :back, notice: 'Questions option was successfully created.' }
        format.json { render json: :back, status: :created, location: @questions_option }
      else
        format.html { render action: "new" }
        format.json { render json: :back.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions_options/1
  # PUT /questions_options/1.json
  def update
    @questions_option = QuestionsOption.find(params[:id])

    respond_to do |format|
      if @questions_option.update_attributes(params[:questions_option])
        format.html { redirect_to @questions_option, notice: 'Questions option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questions_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions_options/1
  # DELETE /questions_options/1.json
  def destroy
    @questions_option = QuestionsOption.find(params[:id])
    @questions_option.destroy

    respond_to do |format|
      format.html { redirect_to questions_options_url }
      format.json { head :no_content }
    end
  end

  private

  def questions_option_params
    params.require(:questions_option).permit(:label, :question_id, :correct)
  end

end

app/helpers/questions_options_helper.rb
module QuestionsOptionsHelper
end

app/views/questions_options/_form.html.haml
- @questions_option = QuestionsOption.new(question_id: @question.id)
= simple_form_for @questions_option do |f|
  - if @questions_option.errors.any?
    #error_explanation
      %h2= "#{pluralize(@questions_option.errors.count, "error")} prohibited this questions_option from being saved:"
      %ul
        - @questions_option.errors.full_messages.each do |msg|
          %li= msg

  .row.pushright
    = f.input :question_id, :as => :hidden
    = f.input :label, :label => 'Valg'
    .pushright
      = f.label :correct, 'Korrekt svar'
      = f.radio_button :correct, 1
    .pushright
      = f.label :correct, 'Forkert svar'
      = f.radio_button :correct, 0
  .row.pushright
    = f.button :submit, :value => 'Gem valgmulighed', :class => 'btn btn-danger'

app/views/questions_options/edit.html.haml
%h1 Editing questions_option
- if current_user.admin?
  = render 'form'

  = link_to 'Show', @questions_option
\|
= link_to 'Back', questions_options_path

app/views/questions_options/index.html.haml
- if current_user.usertype == 9
  %h1 Listing questions_options

  %table
    %tr
      %th Question
      %th Label
      %th
      %th
      %th

    - @questions_options.each do |questions_option|
      %tr
        %td= questions_option.question_id
        %td= questions_option.label
        %td= link_to 'Show', questions_option
        %td= link_to 'Edit', edit_questions_option_path(questions_option)
        %td= link_to 'Destroy', questions_option, method: :delete, data: { confirm: 'Are you sure?' }

  %br

  = link_to 'New Questions option', new_questions_option_path
- else
  = redirect_to root_url

app/views/questions_options/new.html.haml
%h1 New questions_option
- if current_user.admin?
  = render 'form'

= link_to 'Back', questions_options_path

app/views/questions_options/show.html.haml
%p#notice= notice
- if current_user.admin?
  %p
    %b Question:
    = @questions_option.question_id
  %p
    %b Label:
    = @questions_option.label

  = link_to 'Edit', edit_questions_option_path(@questions_option)
\|
= link_to 'Back', questions_options_path