config/routes.rb
Julekalender::Application.routes.draw do
  resources :questions_options

  resources :users
  resources :sessions

  resources :questions

  resources :answers
  match '/signup', to: "users#new", via: [:post,:get]
  match '/login', to: "sessions#new", via: [:post,:get]
  match "logout", to: "sessions#destroy", :as => "logout", via: [:post,:get]

  root :to => 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

end

app/controllers/answers_controller.rb
# encoding: utf-8
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    @option = QuestionsOption.find(params[:answer][:answer])
    #@answer.correct = @option.correct.to_i
    respond_to do |format|
      if @answer.save
        format.html { redirect_to root_url, notice: 'Du har besvaret dangens spørgsmål.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer, :question_id, :user_id, :correct)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.haml
- t = Time.now
- if t.month == 12
  - today = Answer.where("DATE(created_at) = DATE(?)", Time.now).first
  - if today.present?
    - @question = today.question
  - else
    - @question = Question.where('id NOT IN (SELECT question_id FROM answers)').order('rand()').first
    - create = Answer.new(:question_id => @question.id)
    - create.save
  -# @options = QuestionsOption.find_all_by_question_id(@question.id)
  - @answer = Answer.new(:question_id => @question.id)
  .spacer.large
  .row
    .span12
      %h4 Dagens Spørgsmål
      %h5= @question.header
      %p= @question.question
      %p
        Svar
        %br
        = simple_form_for @answer do |f|
          = f.input :user_id, :input_html => {:value => current_user.id}, :as => :hidden
          = f.input :question_id, :as => :hidden
          = f.collection_select :answer, @question.questions_options, :id, :label
          = f.button :submit, :value => 'Indsend svar', :class => 'btn btn-primary'
          = link_to 'Tilbage', root_path, :class => 'btn btn-danger'
- else
  %h3 Julekalenderen åbner først til December

app/views/answers/index.html.haml
- if current_user.usertype == 9
  %h1 Listing answers

  .table
    %tr
      %th User
      %th Question
      %th Answer

  - @answers.each do |answer|
    %tr
      %td= answer.user_id
      %td= answer.question_id
      %td= answer.answer
- else
  = redirect_to root_url

app/views/answers/new.html.haml
= render 'form'

= link_to 'Tilbage', answers_path